# Info
name: support.cufyx.org
title: Cufy Android Support
email: info@cufy.org
description: >-
  A library to support android applications building
  process. It contains common codes, general purpose
  utilities, and helper classes.

# GitHub
github:
  is_project_page: true
  repository_url: https://github.com/cufyx/support
  owner_url: https://github.com/cufyx
  owner_name: Cufy

# Collections
collections:
  fragments:
  pages:
    output: true

# Build
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      favicon: '/assets/logo/framework.ico'
      title: 'Cufy Android Support'